# Generated by Django 4.1.2 on 2022-10-20 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MotherOrganizations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=100)),
                ('name_bn', models.CharField(max_length=100)),
                ('number_of_user', models.IntegerField(default=0)),
                ('has_sister_concern', models.BooleanField(default=False)),
            ],
        ),
    ]
