# Generated by Django 4.1.2 on 2022-10-22 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address_app', '0001_initial'),
        ('organization_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SisterOrganizations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_engalish', models.CharField(max_length=100, null=True)),
                ('name_bangla', models.CharField(max_length=100, null=True)),
                ('address_details', models.CharField(max_length=200, null=True)),
                ('website_address', models.CharField(max_length=200, null=True)),
                ('has_branch_concern', models.BooleanField(default=False)),
                ('district', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sister_organization_districs', to='address_app.districts')),
                ('division', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sister_organization_division', to='address_app.divisions')),
                ('mother_organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sister_mother_organization', to='organization_app.motherorganizations')),
                ('thana', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sister_organization_upazila', to='address_app.upazila')),
            ],
        ),
    ]
