# Generated by Django 4.1.2 on 2022-10-22 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization_app', '0002_sisterorganizations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sisterorganizations',
            old_name='name_bangla',
            new_name='name_bengali',
        ),
        migrations.RenameField(
            model_name='sisterorganizations',
            old_name='name_engalish',
            new_name='name_english',
        ),
    ]
