# Generated by Django 4.1.2 on 2022-10-22 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization_app', '0003_rename_name_bangla_sisterorganizations_name_bengali_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sisterorganizations',
            old_name='thana',
            new_name='upazila',
        ),
    ]
