# Generated by Django 4.1.2 on 2022-10-22 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization_app', '0004_rename_thana_sisterorganizations_upazila'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sisterorganizations',
            name='mother_organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mother_organization_sister_organization', to='organization_app.motherorganizations'),
        ),
    ]
