# Generated by Django 4.1.2 on 2022-10-22 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address_app', '0003_rename_upazila_upazilas'),
        ('organization_app', '0005_alter_sisterorganizations_mother_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_english', models.CharField(max_length=100)),
                ('name_bengali', models.CharField(max_length=100)),
                ('address_details', models.CharField(max_length=200, null=True)),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='branch_districs', to='address_app.districts')),
                ('division', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='branch_division', to='address_app.divisions')),
                ('mother_organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mother_organization_branch', to='organization_app.motherorganizations')),
                ('sister_organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sister_organization_branch', to='organization_app.sisterorganizations')),
                ('upazila', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branch_thana', to='address_app.upazilas')),
            ],
        ),
    ]
