# Generated by Django 4.1.2 on 2022-10-22 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address_app', '0003_rename_upazila_upazilas'),
        ('organization_app', '0006_branches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branches',
            name='mother_organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='branch_mother_organization', to='organization_app.motherorganizations'),
        ),
        migrations.AlterField(
            model_name='branches',
            name='sister_organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='branch_sister_organization', to='organization_app.sisterorganizations'),
        ),
        migrations.AlterField(
            model_name='branches',
            name='upazila',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branch_upazila', to='address_app.upazilas'),
        ),
        migrations.AlterField(
            model_name='sisterorganizations',
            name='mother_organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sister_organization_mother_organization', to='organization_app.motherorganizations'),
        ),
    ]
