# Generated by Django 4.1.2 on 2022-10-22 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='districts',
            old_name='name_bangla',
            new_name='name_bengali',
        ),
        migrations.RenameField(
            model_name='divisions',
            old_name='name_bangla',
            new_name='name_bengali',
        ),
        migrations.RenameField(
            model_name='upazila',
            old_name='name_bangla',
            new_name='name_bengali',
        ),
    ]
