# Generated by Django 4.1.2 on 2022-10-22 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization_app', '0005_alter_sisterorganizations_mother_organization'),
        ('address_app', '0002_rename_name_bangla_districts_name_bengali_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Upazila',
            new_name='Upazilas',
        ),
    ]
