# Generated by Django 4.1.2 on 2022-10-24 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization_app', '0007_alter_branches_mother_organization_and_more'),
        ('rbac_app', '0002_userpermissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermissions',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='permission_branch', to='organization_app.branches'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='mother_organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='permission_mother_organization', to='organization_app.motherorganizations'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='sister_organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='permission_sister_organization', to='organization_app.sisterorganizations'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userpermissions',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='permission_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
