# Generated by Django 4.1.2 on 2022-10-25 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac_app', '0003_userpermissions_branch_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userpermissions',
            unique_together=set(),
        ),
    ]
